/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-10-09 14:13:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddCar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Add New Car</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div><h1>Add your car to the List</h1></div>\n");
      out.write("\t<div style=\"margin-left: 50px; margin-top: 50px; width: 150px;\">\n");
      out.write("\t\t<form name=\"input\" action=\"CarServlet\">\n");
      out.write("\t\t\tMake: \t<select name=\"make\">\n");
      out.write("\t\t\t\t\t\t<option value=\"volvo\">Volvo</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"saab\">Saab</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"fiat\">Fiat</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"audi\">Audi</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\tModel: <input type=\"text\" name=\"model\"><br>\n");
      out.write("\t\t\tYear: <input type=\"text\" name=\"year\"><br>\n");
      out.write("\t\t\tEngine Size: <input type=\"text\" name=\"enginesize\"><br>\n");
      out.write("\t\t\t<input type=\"radio\" name=\"fuel\" value=\"diesel\">Diesel<br>\n");
      out.write("\t\t\t<input type=\"radio\" name=\"fuel\" value=\"petrol\">Petrol<br>\n");
      out.write("\t\t\tPrice: <input type=\"text\" name=\"price\"><br>\n");
      out.write("\t\t\tOther Info: <input type=\"text\" name=\"otherinfo\"><br>\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Submit\">\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
